{% set name = "neptune-xgboost" %}
{% set package_name = "neptune_xgboost" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ package_name }}-{{ version }}.tar.gz
  sha256: ef1848e54651c682f8649404162ba5ab865df2018237fb25200320a4733ddc1f

build:
  noarch: python
  number: 0
  script: '{{ PYTHON }} -m pip install . -vv '

requirements:
  host:
    - pip
    - python >=3.6
    - poetry-core >=1.0.0
    - poetry-dynamic-versioning
  run:
    - matplotlib-base
    - neptune-client >=0.9
    - python >=3.6
    - xgboost >=1.3.0
    - python-graphviz

test:
  imports:
    - neptune_xgboost
    - neptune_xgboost.impl
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://neptune.ai/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Neptune Client integration with XGBoost
  doc_url: https://github.com/neptune-ai/neptune-xgboost/blob/master/README.md
  dev_url: https://github.com/neptune-ai/neptune-xgboost

extra:
  recipe-maintainers:
    - aniezurawski
    - HubertJaworski
    - pitercl
    - Raalsky
    - twolodzko
    - AleksanderWWW
    - PatrykGala
