{% set name = "neptune-xgboost" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/neptune-ai/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 705a37a1a52cd7708b33ade0cbdeea7d53684bda8fa9d370a882f17a5c0f36d6

build:
  noarch: python
  number: 0
  script: '{{ PYTHON }} -m pip install . -vv '

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - matplotlib-base
    - neptune-client >=0.9
    - python >=3.6
    - xgboost >=1.3.0

test:
  imports:
    - neptune_xgboost
    - neptune_xgboost.impl

about:
  home: https://neptune.ai/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Neptune Client integration with XGBoost
  doc_url: https://github.com/neptune-ai/neptune-xgboost/blob/master/README.md
  dev_url: https://github.com/neptune-ai/neptune-xgboost

extra:
  recipe-maintainers:
    - aniezurawski
    - HubertJaworski
    - pitercl
    - PiotrJander
    - shnela
    - pkasprzyk
